name: Build

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=latest
          type=sha,prefix=sha-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build release image
      uses: docker/build-push-action@v6
      with:
        pull: true
        push: true
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
